# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sinopia Tech
description: >- # this means to ignore newlines until "baseurl:"
  This is a page for technical information on the Sinopia project, a RDF-native cataloging environment for LD4P.
baseurl: "/sinopia" # the subpath of your site, e.g. /blog
url: "https://ld4p.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: cmh2166/minimal-architect
plugins:
  - jekyll-feed
  - jekyll-remote-theme

logo: assets/img/logo.jpeg
show_downloads: true
project_wiki: https://wiki.duraspace.org/pages/viewpage.action?pageId=101783799
project_issues: https://waffle.io/LD4P/sinopia

site:
  - github:
    - owner_url: https://github.com/ld4p
    - owner_label: LD4P

menu:
  - menu-label: Requirements & Constraints
    menu-url: /sinopia/requirements
  - menu-label: Glossary
    menu-url: /sinopia/glossary
  - menu-label: Minimum Viable Product
    menu-url: /sinopia/mvp
  - menu-label: External Data Interactions
    menu-url: /sinopia/external-data
  - menu-label: Acceptance Tests
    menu-url: /sinopia/acceptance-tests
  - menu-label: Architecture
    menu-url: /sinopia/architecture
  - menu-label: Implementation
    menu-url: /sinopia/implementation
  - menu-label: Data & Interaction Models
    menu-url: /sinopia/models
  - menu-label: JSON schemas for Profiles and ResourceTemplates
    menu-url: /sinopia/schemas
